# Site
#repository: sproogen/resume-theme
repository: nagyantal9312/nagyantal9312.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Antal Nagy
title: Programmer / Lawyer
email: antalnagywork@gmail.com
website: https://nagyantal9312.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  nagyantal9312
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: antal-nagy-141972194
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-194990893-1"


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Antal Nagy, a multidisciplinary professional with expertise in programming and law. With a background in data protection and information security, I possess a unique blend of technical and legal skills. I thoroughly enjoy creating software and web applications, leveraging my programming proficiency in <mark>PL/SQL</mark>, <mark>Java</mark> and <mark>Python</mark>. As a dedicated programmer and lawyer, I strive to combine my analytical thinking, problem-solving abilities, and attention to detail to deliver innovative solutions. With a passion for technology and a deep understanding of legal frameworks, I am committed to addressing complex challenges and driving impactful outcomes.

  Let's connect and explore how my diverse skill set can contribute to your projects and objectives.
# I am skilled in <mark>GDPR</mark> and <mark>ISO27001</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Python anonymizer
        link: github.com/nagyantal9312/python_anonymizer
        # link_text: Project Website
        additional_links:
          - title:  nagyantal9312/python_anonymizer
            icon: fab fa-github
            url: github.com/nagyantal9312/python_anonymizer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An app which is able to anonymize and pseudonymise data.
        description: | # this will include new lines to allow paragraphs
          This is an application designed to detect and anonymize/pseudonymize personal data. This project initially began during my university years as a means of learning <mark>Pandas</mark> and <mark>Python</mark>. The program effectively identifies personal data and applies anonymization and pseudonymization techniques to protect privacy. It is an <mark>old project</mark>, my current knowledge and experience would enable me to enhance its functionality and performance significantly. I have plans to update and improve the program in the future.   


#   - title: Experience # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: left
#         title: The Boring Company
#         link: boringcompany.com
        # link_text: boringcompany.com
#         sub_title: Senior Network System Administrator
#         caption: November 2017 - Present
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: National Tax and Customs Administration of Hungary
        caption: 2021 - 
        sub_title: Software developer
        quote: >
          NTCA performs the tasks of the state tax authority and customs authority defined by law.
        description: |
          During my tenure as a software developer at NTCA, I gained real-world experience in the field. I had the opportunity to work with <mark>PL/SQL</mark> and <mark>RDBMS</mark>, expanding my knowledge and skills in these areas. I collaborated with a team of professionals to develop and implement software solutions. This enhanced my ability to analyze complex requirements and deliver <mark>high-quality code</mark> within strict deadlines. Moreover, my time at NTCA provided me with a deeper understanding of <mark>large-scale systems</mark> and the importance of adhering to <mark>security and compliance standards</mark>. It has allowed me to apply my technical knowledge to real-world scenarios, and develop a comprehensive understanding of the challenges and opportunities within the public sector.                  

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Google IT Automation with Python
        caption: 2020
        sub_title: Coursera
        quote: >
          https://www.coursera.org/account/accomplishments/professional-cert/TUS5EMF9F8FG
        description: |
          This certificate, developed by Google, is designed to provide IT professionals with in-demand skills -- including Python, <mark>Git</mark>, and IT automation -- that can help them advance their careers. The hands-on curriculum is designed to teach learners how to write code in Python, with a special focus on how this applies to automating tasks in the world of IT support and systems administration.
    
      - layout: left
        title: Google IT Support
        caption: 2020
        sub_title: Coursera
        quote: >          
          https://www.coursera.org/account/accomplishments/professional-cert/87HZZGPGZVJ3
        description: | 
          Those who earn the Google IT Support Professional Certificate have completed five-courses, developed by Google, that include hands-on, practice-based assessments and are designed to prepare them for entry-level roles in IT support. They are competent in foundational skills, including troubleshooting and customer service, networking, operating systems, system administration, and security.
    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Szeged
        caption: 2018 - 2021
        sub_title: BSc Computer Science
        quote: >
          The University of Szeged is one of Hungary's leading and internationally ranked higher education institutions.
        description: | # this will include new lines to allow paragraphs
          Throughout my time as a programming student, I had the opportunity to delve into various programming languages, algorithms, and software development methodologies. These studies not only enhanced my <mark>technical skills</mark> but also sharpened my <mark>problem-solving abilities</mark> and fostered a creative mindset. Moreover, the collaborative nature of the program allowed me to work effectively in teams, building communication and <mark>teamwork skills</mark> that are vital in today's professional world. 
          
      - layout: left
        title: University of Szeged
        caption: 2013 - 2018
        sub_title: Law
        quote: >
          The University of Szeged is one of Hungary's leading and internationally ranked higher education institutions.
        description: | # this will include new lines to allow paragraphs
          Throughout my studies as a lawyer, I delved into various aspects of law, including constitutional law, civil law, criminal law, and administrative law. Beyond the theoretical knowledge, my time at the university honed essential skills that have proven valuable throughout my professional journey like <mark>precision</mark>, attention to detail, and the ability to <mark>handle high-pressure situations</mark>. My education in law not only provided me with a solid legal foundation but also instilled in me a deep appreciation for the rule of law, justice, and the complexities of the legal world.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and programming some of my other interests and hobbies are:
      - Playing the guitar
      - Making cocktails
      - Doing sports

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-analytics

