# Site
#repository: sproogen/resume-theme
repository: nagyantal9312/nagyantal9312.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Antal Nagy
title: Programmer / Lawyer
email: antalnagywork@gmail.com
website: https://nagyantal9312.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  nagyantal9312
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: antal-nagy-141972194
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-194990893-1"


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Antal Nagy and I'm a programmer and a lawyer. I have experience in data protection and information security. I also like making software and web apps.

  My favourite programming languages are: <mark>Java</mark> and <mark>Python</mark>.
# I am skilled in <mark>GDPR</mark> and <mark>ISO27001</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Python anonymizer
        link: github.com/nagyantal9312/python_anonymizer
        # link_text: Project Website
        additional_links:
          - title:  nagyantal9312/python_anonymizer
            icon: fab fa-github
            url: github.com/nagyantal9312/python_anonymizer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An app which is able to anonymize and pseudonymise data.
        description: | # this will include new lines to allow paragraphs
          I started this project during my university years as a way of learning <mark>Pandas</mark> and <mark>Python</mark>. It is an application which is able to detect personal data, and after detection anonymises and/or pseudonymises them. This is an old project, with my current knowledge I could do it much better. I plan to update it in the future.   


#   - title: Experience # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: left
#         title: The Boring Company
#         link: boringcompany.com
        # link_text: boringcompany.com
#         sub_title: Senior Network System Administrator
#         caption: November 2017 - Present
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: National Tax and Customs Administration of Hungary
        caption: 2021 - 
        sub_title: Software developer
        quote: >
          NTCA performs the tasks of the state tax authority and customs authority defined by law.
        description: |
          Working at NTCA as a full stack software developer I had the opportunity to gain real life work experience with <mark>RDMBS</mark> and <mark>PL/SQL</mark>.                  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Szeged
        caption: 2018 - 2021
        sub_title: BSc Computer Science
        quote: >
          The University of Szeged is one of Hungary's leading and internationally ranked higher education institutions.
        description: | # this will include new lines to allow paragraphs
          During my time as a programmer student I became a better team player. In addition to that, studying programming significantly improved my problem solving skills and creativity.
          
      - layout: left
        title: University of Szeged
        caption: 2013 - 2018
        sub_title: Law
        quote: >
          The University of Szeged is one of Hungary's leading and internationally ranked higher education institutions.
        description: | # this will include new lines to allow paragraphs
          During my time as a law student I learnt a lot of key skills that have I have taken through my career such as precision and stress tolerance. I thouroughly enjoyed my time there and learnt a lot about the laws of my country.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and programming some of my other interests and hobbies are:
      - Playing the guitar
      - Making cocktails
      - Doing sports

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-analytics

